FORMS += \
    $$PWD/commonuiset/messagedialog/messagedialog.ui \
    $$PWD/commonuiset/table/tablewidget.ui \
    $$PWD/configuiset/adminlogindialog.ui \
    $$PWD/configuiset/camsetdialog.ui \
    $$PWD/configuiset/configdialog.ui \
    $$PWD/configuiset/logdialog.ui \
    $$PWD/configuiset/materialsetdialog.ui \
    $$PWD/configuiset/ordersetdialog.ui \
    $$PWD/configuiset/passworddialog.ui \
    $$PWD/configuiset/rectdialog.ui \
    $$PWD/configuiset/signdialog.ui \
    $$PWD/configuiset/unitdialog.ui \
    $$PWD/mainuiset/aboutdialog.ui \
    $$PWD/mainuiset/aboutdialog1.ui \
    $$PWD/mainuiset/buttonwidget.ui \
    $$PWD/mainuiset/imageviews/fourviewswidget.ui \
    $$PWD/mainuiset/imageviews/imageview.ui \
    $$PWD/mainuiset/imageviews/singleviewwidget.ui \
    $$PWD/mainuiset/imageviews/viewtoolbar.ui \
    $$PWD/mainuiset/infowidget.ui \
    $$PWD/mainuiset/logwidget.ui \
    $$PWD/mainuiset/mainframe.ui \
    $$PWD/mainuiset/operationalcontrolwidget.ui \
    $$PWD/mainuiset/statisticswidget.ui \
    $$PWD/mainuiset/titlebarwidget.ui

HEADERS += \
    $$PWD/commonuiset/imagegraphics/imagegraphicsitem.h \
    $$PWD/commonuiset/imagegraphics/imagegraphicsscene.h \
    $$PWD/commonuiset/imagegraphics/imagegraphicsview.h \
    $$PWD/commonuiset/messagedialog/messagedialog.h \
    $$PWD/commonuiset/messagedialog/messagedialogtitlebar.h \
    $$PWD/commonuiset/table/tablemodel.h \
    $$PWD/commonuiset/table/tablewidget.h \
    $$PWD/configuiset/adminlogindialog.h \
    $$PWD/configuiset/camsetdialog.h \
    $$PWD/configuiset/configdialog.h \
    $$PWD/configuiset/configtitlebar.h \
    $$PWD/configuiset/logdialog.h \
    $$PWD/configuiset/materialsetdialog.h \
    $$PWD/configuiset/ordersetdialog.h \
    $$PWD/configuiset/passworddialog.h \
    $$PWD/configuiset/rectdialog.h \
    $$PWD/configuiset/signdialog.h \
    $$PWD/configuiset/unitdialog.h \
    $$PWD/mainuiset/aboutdialog.h \
    $$PWD/mainuiset/aboutdialog1.h \
    $$PWD/mainuiset/buttonwidget.h \
    $$PWD/mainuiset/imageviews/fourviewswidget.h \
    $$PWD/mainuiset/imageviews/imageview.h \
    $$PWD/mainuiset/imageviews/singleviewwidget.h \
    $$PWD/mainuiset/imageviews/viewtoolbar.h \
    $$PWD/mainuiset/infowidget.h \
    $$PWD/mainuiset/logwidget.h \
    $$PWD/mainuiset/mainframe.h \
    $$PWD/mainuiset/operationalcontrolwidget.h \
    $$PWD/mainuiset/statisticswidget.h \
    $$PWD/mainuiset/titlebarwidget.h

SOURCES += \
    $$PWD/commonuiset/imagegraphics/imagegraphicsitem.cpp \
    $$PWD/commonuiset/imagegraphics/imagegraphicsscene.cpp \
    $$PWD/commonuiset/imagegraphics/imagegraphicsview.cpp \
    $$PWD/commonuiset/messagedialog/messagedialog.cpp \
    $$PWD/commonuiset/messagedialog/messagedialogtitlebar.cpp \
    $$PWD/commonuiset/table/tablemodel.cpp \
    $$PWD/commonuiset/table/tablewidget.cpp \
    $$PWD/configuiset/adminlogindialog.cpp \
    $$PWD/configuiset/camsetdialog.cpp \
    $$PWD/configuiset/configdialog.cpp \
    $$PWD/configuiset/configtitlebar.cpp \
    $$PWD/configuiset/logdialog.cpp \
    $$PWD/configuiset/materialsetdialog.cpp \
    $$PWD/configuiset/ordersetdialog.cpp \
    $$PWD/configuiset/passworddialog.cpp \
    $$PWD/configuiset/rectdialog.cpp \
    $$PWD/configuiset/signdialog.cpp \
    $$PWD/configuiset/unitdialog.cpp \
    $$PWD/mainuiset/aboutdialog.cpp \
    $$PWD/mainuiset/buttonwidget.cpp \
    $$PWD/mainuiset/imageviews/fourviewswidget.cpp \
    $$PWD/mainuiset/imageviews/imageview.cpp \
    $$PWD/mainuiset/imageviews/singleviewwidget.cpp \
    $$PWD/mainuiset/imageviews/viewtoolbar.cpp \
    $$PWD/mainuiset/infowidget.cpp \
    $$PWD/mainuiset/logwidget.cpp \
    $$PWD/mainuiset/mainframe.cpp \
    $$PWD/mainuiset/operationalcontrolwidget.cpp \
    $$PWD/mainuiset/statisticswidget.cpp \
    $$PWD/mainuiset/titlebarwidget.cpp

DISTFILES += \
    $$PWD/font/PingFangRegular.ttf \
    $$PWD/images/aboutdialog/close.svg \
    $$PWD/images/aboutdialog/logo.svg \
    $$PWD/images/camera_config/Success.svg \
    $$PWD/images/camera_config/catch_once.svg \
    $$PWD/images/camera_config/catch_once_active.svg \
    $$PWD/images/camera_config/off.svg \
    $$PWD/images/camera_config/on.svg \
    $$PWD/images/camera_config/pause.svg \
    $$PWD/images/camera_config/refresh.svg \
    $$PWD/images/camera_config/refresh_disabled.svg \
    $$PWD/images/camera_config/revert.svg \
    $$PWD/images/camera_config/start.svg \
    $$PWD/images/camera_config/stream.svg \
    $$PWD/images/camera_config/stream_active.svg \
    $$PWD/images/camera_config/waiting.gif \
    $$PWD/images/camera_config/zoomin_disabled.svg \
    $$PWD/images/camera_config/zoomin_enabled.svg \
    $$PWD/images/camera_config/zoomout_disabled.svg \
    $$PWD/images/camera_config/zoomout_enabled.svg \
    $$PWD/images/common/menu.png \
    $$PWD/images/config/add.svg \
    $$PWD/images/config/camera_icon.svg \
    $$PWD/images/config/close.svg \
    $$PWD/images/config/delete.svg \
    $$PWD/images/config/image_source.svg \
    $$PWD/images/config/model_icon.svg \
    $$PWD/images/config/no_selected.svg \
    $$PWD/images/config/save_icon.svg \
    $$PWD/images/config/selected.svg \
    $$PWD/images/config/sys_icon.svg \
    $$PWD/images/config/view_icon.svg \
    $$PWD/images/ico/admin.ico \
    $$PWD/images/ico/cam.ico \
    $$PWD/images/ico/log.ico \
    $$PWD/images/ico/material.ico \
    $$PWD/images/ico/order.ico \
    $$PWD/images/ico/p.ico \
$$PWD/images/ico/stereoscopiccam.ico\
    $$PWD/images/imageview/background.png \
    $$PWD/images/logo.ico \
    $$PWD/images/mainlogo.bmp \
    $$PWD/images/model_config/off.svg \
    $$PWD/images/model_config/on.svg \
    $$PWD/images/model_config/question_mark.svg \
    $$PWD/images/operationalcontrolwidget/cycle_disabled.svg \
    $$PWD/images/operationalcontrolwidget/cycle_run.svg \
    $$PWD/images/operationalcontrolwidget/cycle_stop.svg \
    $$PWD/images/operationalcontrolwidget/once_disabled.svg \
    $$PWD/images/operationalcontrolwidget/once_run.svg \
    $$PWD/images/operationalcontrolwidget/once_stop.svg \
    $$PWD/images/operationalcontrolwidget/p.ico \
    $$PWD/images/operationalcontrolwidget/pause.svg \
    $$PWD/images/operationalcontrolwidget/pause_disabled.svg \
    $$PWD/images/operationalcontrolwidget/pauset.png \
    $$PWD/images/operationalcontrolwidget/pauset.svg \
    $$PWD/images/operationalcontrolwidget/s.ico \
    $$PWD/images/operationalcontrolwidget/start.png \
    $$PWD/images/operationalcontrolwidget/start.svg \
    $$PWD/images/tableview/nodata.svg \
    $$PWD/images/titlebar/ch.svg \
    $$PWD/images/titlebar/close.svg \
    $$PWD/images/titlebar/config.svg \
    $$PWD/images/titlebar/config_disabled.svg \
    $$PWD/images/titlebar/en.svg \
    $$PWD/images/titlebar/max.svg \
    $$PWD/images/titlebar/min.svg \
    $$PWD/images/titlebar/restore.svg \
    $$PWD/images/titlebar/version.svg \
    $$PWD/images/viewstatusbar/NG.svg \
    $$PWD/images/viewstatusbar/OK.svg \
    $$PWD/images/viewstatusbar/left.svg \
    $$PWD/images/viewstatusbar/left_disabled.svg \
    $$PWD/images/viewstatusbar/right.svg \
    $$PWD/images/viewstatusbar/right_disabled.svg \
    $$PWD/images/viewtoolbar/ai_image_dispaly.svg \
    $$PWD/images/viewtoolbar/camera.svg \
    $$PWD/images/viewtoolbar/camera_active.svg \
    $$PWD/images/viewtoolbar/camera_disconnect.svg \
    $$PWD/images/viewtoolbar/camera_off.svg \
    $$PWD/images/viewtoolbar/camera_on.svg \
    $$PWD/images/viewtoolbar/import.svg \
    $$PWD/images/viewtoolbar/restore.svg \
    $$PWD/images/viewtoolbar/src_image_dispaly.svg \
    $$PWD/images/viewtoolbar/zoomin.svg \
    $$PWD/images/viewtoolbar/zoomout.svg \
    $$PWD/style/stylesheet.qss \
    $$PWD/translations/smore_vimo_en.qm \
    $$PWD/translations/smore_vimo_en.ts \
    $$PWD/translations/smore_vimo_zh-cn.qm \
    $$PWD/translations/smore_vimo_zh-cn.ts
